### ISSUE TITLE
Separate communication layer from high level endpoints

### ISSUE THREAD

**Issue by MtzwOsk** [community-phone-company/shipbob-sdk-python#8]
ShipBob Client as inheritance class shouldn't be couple with session, communication layer. 
I see reason that we can change the requests on some other library: faster, newest.  

MAX_REQUESTS_PER_MINUTE should be also sets in env with default it help to fast reaction for changed behaviour of api without changes in code. We avoid to update of version of package.

MAX_PAGE_SIZE is not neccery info for requests/http comuncation.  
Valid Range is 1 to 250 with a default of 50, that flexible so we should let user to use chose that range, and validate for MAX_PAGE_SIZE from env.

Current ShipBobClient should coints only request method and config to setup requests behaviour. Rename class to ComunicationLayer for instance.  

ShipBobClient should have only high level comunication methods - specifices endpoints shipbob API, and need to be seprate from ComunicationLayer. Comunication need to be injection inside that instance.

Using sleep function in one thread is high costed, it will blocks running when some other stuff can be do. 
Its better to comunicate clear to high level user that he must wait, so raising error, and catch state of time in Communication Layer. 
Both classes shoulde have abstract layer and clear abstractmethod, open to extends.

**Comment by lullis** [comment]
I guess you are not familiar with ShipBob API. The PAGE SIZE limitation is something that happens on their side. It can not be something selected by the client, because you can not request more than 250 items at a time.

As for using sleep, you are obviously right that it blocks the thread, but the idea here is *exactly* that the client needs to slow down its processing because it is hit the limits of the server. 

I´d accept the argument that if you want to have a non-blocking http client, you'd use something based on asyncio. But your proposed solution does not mention any of that and instead makes a bad assumption about how the code works.
